### ISSUE TITLE
Reimplement teams_controller.rb

### ISSUE THREAD

**Issue by ReubenVandezande** [nitinjoseph11/reimplementation-back-end#1]
## Background:
The teams_controller.rb file contains operations on teams like listing of teams of an assignment/course, updating a team, deleting teams of an assignment/course, copying teams between two assignments or courses among others. The model team.rb contains a lot of functions, with probable violations of single responsibility principle and this needs to be reimplemented with care. The files do not benefit from the complex names the functions are given.

### Emphasize on Single Responsibility Principle
There are a questionable amount of functions that are directed at copying teams and team members between parents (courses/assignments). There are a lot of class functions in the model, which could be bad design. While reimplementing, make sure that SRP is maintained. See if any code is repetitive, and can be cut down.

### Improve naming 
Some functions have confusing names. For example, the function “bequeath_copy” can definitely be given a better name if the functionality needs to be reimplemented. The over-populated “copy” related functions in this controller decrease the readability of the code.

### Better comments 
Bigger files and functions require better comments for readability.

**Comment by ReubenVandezande** [comment]
## Initial thoughts on the new model
@nitinjoseph11 Let me know what else we might need to consider

We will need to generate a new model and controller: TeamAssignment, TeamsAssignmentController.
The TeamAssignment model will need a database schema with a minimum of a team and assignment reference:

`rails generate scaffold TeamAssignment team:reference  assignment:reference`

In addition, the team model will need to have a team assignment and the Assignment needs to reference a team:

`rails generate migration AddTeamAssignmentRefToTeam team_assignment:reference`
`rails generate migration AddTeamAssignmentRefToAssignment team_assignment:reference`

**Comment by nitinjoseph11** [comment]
The database schema will be 

create_table "teams", id: :integer, force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=latin1" do |t|
    t.string "name"
    t.integer "parent_id"
    t.string "type"
    t.text "comments_for_advertisement"
    t.boolean "advertise_for_partner"
    t.text "submitted_hyperlinks"
    t.integer "directory_num"
    t.integer "grade_for_submission"
    t.text "comment_for_submission"
    t.integer "pair_programming_request", limit: 1
  end
  
 also, we will need to add the corresponding addition to the seeds.rb file, which will run when a post query is sent on Postman which should fetch us the db contents there which would mean the backend works fine. 

We also need to write corresponding rspec tests for model and controller. 

Reference to implement controller and model should be courses controller and model. Most functions can be reused with changes.
